name: CI-Workflow

on:
  push:
    branches:
      - main

env:
  ENV_NAME: ci1

jobs:
  call-workflow:
    uses: chrisowen491/ReusableActions/.github/workflows/build_deploy_test_lambda_via_sam.yaml@main
    with:
      env: $ENV_NAME
      stack_name: DynamicPage-$ENV_NAME
      repository: ${{ github.repository }}
      base_url: https://api.$ENV_NAME.tranmere-web.com/page/
    secrets: inherit